### ISSUE TITLE
Switch from Google to Mandrill for notifications emails

### ISSUE THREAD

**Issue by fma2** [BetaNYC/citygram-nyc#14]

**Comment by dirkkelly** [comment]
### [CodeForAmerica branch](https://citygram-nyc-codeforamerica.herokuapp.com)

```
heroku config:set SMTP_ADDRESS=smtp.mandrillapp.com SMTP_DOMAIN=beta.nyc SMTP_FROM_ADDRES=notifications@beta.nyc SMTP_USER_NAME=citygram@dirkkelly.com SMTP_PASSWORD=LOLOLOLOL-a citygram-nyc-codeforamerica
```

![citygram-nyc-codeforamerica Mandrill Settings Preview (CENSORED)](https://cloud.githubusercontent.com/assets/81055/6262259/d3367f38-b7cd-11e4-8efe-8d50a40218d7.png)

**Comment by dirkkelly** [comment]
:+1: cool that seems to be loading.

### [Staging branch](https://citygram-nyc-staging.herokuapp.com)

**CENSORED**

```
heroku config:set SMTP_ADDRESS=smtp.mandrillapp.com SMTP_DOMAIN=beta.nyc SMTP_FROM_ADDRES=notifications@beta.nyc SMTP_USER_NAME=citygram@dirkkelly.com SMTP_PASSWORD=LOLOLOLOL-a citygram-nyc-staging
```

:+1: also this is now loading

**Comment by dirkkelly** [comment]
Going to try send an email to me from staging, check that it doesn't send to me and does go to Mandrill.

After fixing the console

```
heroku run rake console -a iex-app-codeforamerica

email = Citygram::Services::Channels::Email.mail({to: "citygram@dirkkelly.com"})
      #<Mail::Message:69899564145940, Multipart: false, Headers: <Date: Thu, 19 Feb 2015 05:46:35 +0000>, <From: notifications@beta.nyc>, <To: citygram@dirkkelly.com>, <Message-ID: <54e578bb52b0_33f92c0aefe9c709ae@5e71c83f-5942-42b8-be65-2155cf6cd205.mail>>, <Mime-Version: 1.0>, <Content-Type: text/plain>, <Content-Transfer-Encoding: 7bit>>

email.body
      #<Mail::Body:0x007f2585676018 @boundary=nil, @preamble=nil, @epilogue=nil, @charset="US-ASCII", @part_sort_order=["text/plain", "text/enriched", "text/html"], @parts=[], @raw_source="", @encoding="7bit">
```

**Comment by dirkkelly** [comment]
server isn't booting

```
2015-02-19T06:02:02.460106+00:00 app[web.1]: Sequel::DatabaseError - PG::UndefinedColumn: ERROR:  column "tags" does not exist
2015-02-19T06:02:02.460151+00:00 app[web.1]: LINE 1: ... TRUE) AND ("visible" IS TRUE) AND ('seattle' = ANY (tags)))
2015-02-19T06:02:02.460154+00:00 app[web.1]:
```

so I gotta migrate? hrm can't.

```
$ heroku run rake db:migrate -a citygram-nyc-codeforamerica
/Users/dirkkelly/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg_backups.rb:64: warning: already initialized constant MaybeAttachment
Running `rake db:migrate` attached to terminal... up, run.6282
```

**Comment by dirkkelly** [comment]
Find my subscription

```
$ heroku run rake console -a citygram-nyc-staging
  subscription = Subscription.where(channel: "email", email_address: "citygram@dirkkelly.com").first
  Citygram::Services::Channels::Email.call(subscription, nil)
```

So I didn't receive an email, that's good (because this is staging), but I need to find it in mandrill.

Excellent, I got into the test mode in Mandrill

![screen shot 2015-02-19 at 1 14 49 am](https://cloud.githubusercontent.com/assets/81055/6262596/b91b7a84-b7d4-11e4-9086-61e686e3c89f.png)

Oh woah! There they are

![screen shot 2015-02-19 at 1 14 23 am](https://cloud.githubusercontent.com/assets/81055/6262599/da405ee6-b7d4-11e4-97de-6a08a389e92b.png)

okay, so we have test emails going out from `staging` and `codeforamerica`

**Comment by dirkkelly** [comment]
:+1: imo this is working in staging, so we should swap it over for production and give it a go next week, check results wednesday morning.

cc/ @noneck @fma2

**Comment by dirkkelly** [comment]
![1416530385-18fz1zxxbtovqjpg](https://cloud.githubusercontent.com/assets/81055/6262742/79a09ec2-b7d7-11e4-8e84-a8e7195068f6.jpg)

Making it live

```
heroku config:set SMTP_ADDRESS=smtp.mandrillapp.com SMTP_DOMAIN=beta.nyc SMTP_FROM_ADDRES=notifications@beta.nyc SMTP_USER_NAME=citygram@dirkkelly.com SMTP_PASSWORD=LOLOLOL -a citygram-nyc
```

Cool, it boots.

Time to subscribe.

We'll need to get some domain signing, but it's working. Note via: mandrillapp.com

![screen shot 2015-02-19 at 1 36 54 am](https://cloud.githubusercontent.com/assets/81055/6262764/d7fbc230-b7d7-11e4-9312-ad157f6a0648.png)
