### ISSUE TITLE
CodeAcross Presentation

### ISSUE THREAD

**Issue by dirkkelly** [BetaNYC/citygram-nyc#31]
# Current Team

### [Dirk Kelly @dirkkelly](https://github.com/dirkkelly)

Took over this project 2 weeks ago after Noel requested a new maintainer at a BetaNYC hacknight.

### [Farheen Malik @fma2](https://github.com/fma2)

Also took on this project 2 weeks ago, has been manually executing 

### [Ryan Malecky @rmalecky](https://github.com/rmalecky)

Introduced himself today at #codeacross, will be looking at how we can add new data sources to https://www.citygram.nyc

### You?

# Required Roles

[https://www.citygram.nyc/civic.json](https://www.citygram.nyc/civic.json)

```
  "needs": [
    {"need": "Web Designer"},
    {"need": "Data Scientist"}
  ]
```

## NYC

# Goals

## Introduce more data feeds

![current feeds](https://cloud.githubusercontent.com/assets/81055/6315197/31f3d682-b9c8-11e4-9181-e72f726d6a46.png)

## Separate out 311 information

[![other feeds](https://cloud.githubusercontent.com/assets/81055/6315212/b6ea1c8e-b9c8-11e4-91d3-b623de3a6ec3.png)](https://data.cityofnewyork.us/)

[https://data.cityofnewyork.us/](https://data.cityofnewyork.us/)

## Move to a single project

* https://www.citygram.org | https://github.com/codeforamerica/citygram
* https://www.citygram.org | https://github.com/citygram/citygram
* https://www.citygram.nyc | https://github.com/betanyc/citygram-nyc

### Automate the non-automatic weekly notifications

Currently we're running `heroku run rake digests:send` in order to send out the weekly digests, the upstream project has a coded concept of which day to run the updates on, if we can get back to that branch we can set our cron task to run the script automatically.

# Challenges

## Upstream `codeforamerica` has no maintainer 

[![no maintainer](https://cloud.githubusercontent.com/assets/81055/6315206/87b746ee-b9c8-11e4-809e-8ad74da98f2b.png)](https://github.com/codeforamerica/citygram/pull/155#issuecomment-73130470)

[https://github.com/codeforamerica/citygram/pull/155#issuecomment-73130470](https://github.com/codeforamerica/citygram/pull/155#issuecomment-73130470)

### BetaNYC

[![citygram.nyc](https://cloud.githubusercontent.com/assets/81055/6315202/62ef68f0-b9c8-11e4-95ac-e2e72fd5c821.png)](https://www.citygram.nyc)

[https://www.citygram.nyc](https://www.citygram.nyc)

### CodeForAmerica

[![citygram.org/new-york](https://cloud.githubusercontent.com/assets/81055/6315204/6cabce9c-b9c8-11e4-85be-102c949bb8b4.png)](https://www.citygram.org/new-york)

[https://www.citygram.org/new-york](https://www.citygram.org/new-york)

# Current Efforts

## citygram-nyc-codeforamerica [Pull #25](https://github.com/BetaNYC/citygram-nyc/pull/25)

In order to get back to the root codebase we need to cherry-pick our changes back into their master branch. We have a copy of this branch currently **not** running at https://citygram-nyc-codeforamerica.herokuapp.com. The current issue is that we [can't run migrations](https://github.com/BetaNYC/citygram-nyc/issues/29)

**Comment by bigfleet** [comment]
Hey, gang!  I am installed now as the maintainer of codeforamerica/citygram

I would welcome bringing NY back to citygram.org/new-york if you liked.  I would encourage you to remain independent if you had any desire to do so.  Strong brigades ought not to be bottlenecked by a volunteer maintainer of the entire project.

Regarding bringing the code changes in, I'm now ready to look at pull requests.

**Comment by dirkkelly** [comment]
@bigfleet fantastic news!

I think there's huge value in us being an instance of this project outside of the codeforamerica instance, ultimately we're all going to be encouraging other cities to use this tool and we'll be able to serve as an example of this independence.

I'm absolutely focused on bringing our codebase back in line with coa's though, and once that happens we're going to need to figure out how we retain the domain citygram.nyc without the /new-york.

I think there's an opportunity for us to keep the sense of a directory of all cities, whilst allowing those who are interested to self host under their own domain. This will require some development efforts and I'd be really happy to be involved in that.
