### ISSUE TITLE
Join the the CityGram discussion group on Talk.beta.NYC

### ISSUE THREAD

**Issue by noneck** [BetaNYC/citygram-nyc#42]
If you can, please join [talk.beta.nyc](https://talk.beta.nyc/c/working-groups/citygram).

**Comment by fma2** [comment]
+1

**Comment by dirkkelly** [comment]
<img width="705" alt="screen shot 2015-07-29 at 8 28 31 pm" src="https://cloud.githubusercontent.com/assets/81055/8973207/6712ce42-3630-11e5-9734-79e6b547ac4d.png">

![clevergirl](https://cloud.githubusercontent.com/assets/81055/8973222/80be0c8a-3630-11e5-9d07-cb78910e04e2.jpg)
