### ISSUE TITLE
Extract, transform load tools

### ISSUE THREAD

**Issue by volkanunsal** [BetaNYC/citygram-nyc#53]
There is a cool project I want to recommend for extracting, transforming and loading data sources from multiple sources to a postgres database called [pgloader](http://pgloader.io/howto/pgloader.1.html). You can write a SQL-like transformation files that look kind of like this:

```
LOAD DATABASE  
     FROM      mysql://root@localhost/sakila  
     INTO postgresql://localhost:54393/sakila  
 
 WITH include drop, create tables, create indexes, reset sequences  
 
  SET maintenance_work_mem to '128MB',  
      work_mem to '12MB',  
      search_path to 'sakila'  
 
 CAST type datetime to timestamptz drop default drop not null using zero-dates-to-null,  
      type date drop not null drop default using zero-dates-to-null,  
      -- type tinyint to boolean using tinyint-to-boolean,  
      type year to integer  
 
 MATERIALIZE VIEWS film_list, staff_list  
 
 -- INCLUDING ONLY TABLE NAMES MATCHING ~/film/, 'actor'  
 -- EXCLUDING TABLE NAMES MATCHING ~<ory>  
 -- DECODING TABLE NAMES MATCHING ~/messed/, ~/encoding/ AS utf8  
 
 BEFORE LOAD DO  
 $$ create schema if not exists sakila; $$; 
```

There is another project called [dat](http://dat-data.com/) that we are planning to implement for our data portal. I might be wrong, but that's some way off for the time being –– @jqnatividad correct me if I'm wrong.

**Comment by fma2** [comment]
Thanks @volkanunsal !  Can you post this in the citygram-services-nyc repo: https://github.com/BetaNYC/citygram-services-nyc/issues?
