### ISSUE TITLE
Background is slow to load and site is hard to read until it is loaded

### ISSUE THREAD

**Issue by excepttheweasel** [BetaNYC/citygram-nyc#67]
This could probably be improved a lot, for me it takes around 3 seconds to load the background

<img width="1280" alt="screen shot 2015-07-25 at 17 37 26" src="https://cloud.githubusercontent.com/assets/344071/8891355/0f6fb306-32f4-11e5-9252-a138eff6d48d.png">

It's 1.4mb and while it looks great, that's probably too big. 

My suggestions would be:
  1. Prefer a jpeg over png, some lossiness won't matter here
  2. Set the background of the page without the image to a color similar to that in the image, that way until it loads you can at least read the white text.
  3. Try to load the image earlier
  4. Get the image on a faster CDN? (don't know about cloud.githubusercontent, maybe it's good enough)

**Comment by excepttheweasel** [comment]
https://github.com/codeforamerica/citygram/pull/195

**Comment by dirkkelly** [comment]
Merged
