### ISSUE TITLE
Add civic.json file

### ISSUE THREAD

**Issue by noneck** [BetaNYC/citygram-nyc#7]

**Comment by dirkkelly** [comment]
Can you clarify this?

**Comment by noneck** [comment]
https://github.com/BetaNYC/civic.json

This repo needs a civic.json file so it can appear on the betaNYC projects page.

**Comment by dirkkelly** [comment]
Cheers :smile:

**Comment by dirkkelly** [comment]
We're good!

http://opengovhacknight.org/projects.html#/?search=citygram

![screen shot 2015-02-19 at 1 30 25 am](https://cloud.githubusercontent.com/assets/81055/6262706/e9d674a6-b7d6-11e4-9f52-2f1bc8387c41.png)
