### ISSUE TITLE
Installation Guide inconsistency

### ISSUE THREAD

**Issue by elberdev** [BetaNYC/citygram-nyc#73]
In Readme.md under "Install Dependencies" the instructions did not work for me as written. 

Instead of:

git clone https://github.com/codeforamerica/citygram.git
cd citygram
rbenv install local
brew install postgresql postgis
gem install bundler
bundle install

I had to do:

git clone https://github.com/codeforamerica/citygram.git
cd citygram
rbenv install local
brew install postgresql postgis
gem install bundler
rbenv rehash
bundle install

I had to run "rbenv rehash" before "bundle install". Otherwise bash did not recognize the "bundle install" command.

If I get the repo working I'll go in and fix this myself + do a pull request

**Comment by dirkkelly** [comment]
Cheers for reporting.

You get it working? A pull request would be great!

Thanks

**Comment by elberdev** [comment]
Hey Dirk, looks good! I sent a couple of minor tweaks to the install instructions in a separate pull request. Sorry for the delay in communication.

**Comment by dirkkelly** [comment]
@elberdev Thanks mate!
