### ISSUE TITLE
Automate weekly email digest

### ISSUE THREAD

**Issue by dirkkelly** [BetaNYC/citygram-nyc#8]
Currently executed from a heroku authed dev machine with

```
heroku run rake digests:send
```

**Comment by dirkkelly** [comment]
Possibility to use scheduler, more recent version of citygram supports configuring the day of the week to send on https://github.com/codeforamerica/citygram/commit/4c2533ba3e8cbdba16c6be8d19be42adf9225855#diff-b2041cec6cc741dec054652f4570ced0

**Comment by dirkkelly** [comment]
And of course I forgot to do this today.

@fma2 from a users perspective would you prefer it now or Thursday morning?

**Comment by fma2** [comment]
Thursday morning

**Comment by dirkkelly** [comment]
:warning:  this is blocked off rebasing from `codeforamerica/master` where we will have access to https://github.com/codeforamerica/citygram/commit/4c2533ba3e8cbdba16c6be8d19be42adf9225855

**Comment by fma2** [comment]
So, until wet get it fixed, I have a Google Now reminder telling me to do it on Wednesday morning.

**Comment by dirkkelly** [comment]
@fma2 thanks for that, you're a champion. I'll be presenting on citygram-nyc today at codeacross, you can view it here https://github.com/BetaNYC/citygram-nyc/issues/31

**Comment by dirkkelly** [comment]
w00t did this one
