### ISSUE TITLE
Add noel to Heroku CityGram.nyc account

### ISSUE THREAD

**Issue by noneck** [BetaNYC/citygram-nyc#9]
Can you please add free.stuff@beta.nyc as a collaborator?

**Comment by noneck** [comment]
Sorry, assigning this to @fma2

**Comment by fma2** [comment]
Just added free.stuff@beta.nyc as a collaborator on Heroku!  Let me know if it worked

**Comment by noneck** [comment]
@fma2 Not yet. I will check back at hacknight
