### ISSUE TITLE
SSL error on production

### ISSUE THREAD

**Issue by dirkkelly** [BetaNYC/citygram-nyc#96]
We've moved to cloudflare, our DNS settings weren't accurate in that they pointed to the heroku ssl endpoint, but must point to the public endpoint.

https://robots.thoughtbot.com/set-up-cloudflare-free-ssl-on-heroku

**Comment by dirkkelly** [comment]
Wrong

<img width="948" alt="screen shot 2015-10-20 at 3 55 53 pm" src="https://cloud.githubusercontent.com/assets/81055/10619330/10c294c4-7743-11e5-9b70-58191d830669.png">

Right

<img width="1012" alt="screen shot 2015-10-20 at 3 54 22 pm" src="https://cloud.githubusercontent.com/assets/81055/10619325/080bf15e-7743-11e5-9cd2-3ba433cc5b97.png">

**Comment by dirkkelly** [comment]
<img width="326" alt="screen shot 2015-10-20 at 3 57 50 pm" src="https://cloud.githubusercontent.com/assets/81055/10619370/5586e696-7743-11e5-9477-222c93a509be.png">

**Comment by dirkkelly** [comment]
Boom, scud storm.

<img width="1083" alt="screen shot 2015-10-20 at 3 59 02 pm" src="https://cloud.githubusercontent.com/assets/81055/10619401/7f205992-7743-11e5-944d-2478d21b7816.png">

**Comment by dirkkelly** [comment]
<img width="746" alt="screen shot 2015-10-20 at 4 00 36 pm" src="https://cloud.githubusercontent.com/assets/81055/10619449/ba5201dc-7743-11e5-8a0e-dd15fefc7634.png">

**Comment by noneck** [comment]
:+1:
